# Generated by Django 3.1.14 on 2022-01-02 19:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0002_auto_20220103_0035'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personal_todo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_on', models.DateTimeField(auto_now_add=True)),
                ('todo_name', models.CharField(max_length=50)),
                ('date', models.DateField()),
                ('tag', models.CharField(max_length=20)),
                ('finish_flag', models.BooleanField(default=False)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='personal_todo', to='accounts.user')),
            ],
            options={
                'verbose_name': 'Todo',
                'verbose_name_plural': 'Todos',
                'ordering': ['-created_on'],
            },
        ),
    ]
