# Generated by Django 3.1.14 on 2022-01-03 17:28

import accounts.models
from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=30, unique=True)),
                ('realname', models.CharField(max_length=30)),
                ('phone_num', models.CharField(max_length=11)),
                ('email_agree', models.BooleanField(default=False)),
                ('sns_agree', models.BooleanField(default=False)),
                ('username', models.CharField(max_length=20, unique=True)),
                ('jobs', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '대학생'), (2, '취준생'), (3, '주니어 직장인'), (4, '시니어 직장인')], max_length=7, null=True)),
                ('interests', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, '운동 & 건강'), (2, '자격증'), (3, '코딩 공부'), (4, '디자인'), (5, '관심분야1'), (6, '관심분야2')], max_length=11, null=True)),
                ('is_superuser', models.BooleanField(default=False)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
                'managed': True,
            },
            managers=[
                ('objects', accounts.models.UserManager()),
            ],
        ),
    ]
