# Generated by Django 3.1.14 on 2022-01-16 15:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='jobs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('대학생', '대학생'), ('대학생', '취준생'), ('주니어 직장인', '주니어 직장인'), ('주니어 직장인', '시니어 직장인')], max_length=23, null=True),
        ),
    ]
