# Generated by Django 3.1.14 on 2022-01-16 16:25

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='interests',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('lang_en', '영어'), ('lang_zh', '중국어'), ('lang_ja', '일본어'), ('lang_es', '스페인어'), ('life_fa', '패션'), ('life_be', '뷰티'), ('life_ac', '연기'), ('life_da', '춤'), ('com_co', '코딩'), ('com_da', '데이터 분석'), ('com_ed', '영상 편집'), ('ge_cu', '요리'), ('ge_ex', '운동'), ('ge_ca', '캘리그라피'), ('ge_ge', '교양'), ('art_mu', '음악'), ('art_cr', '공예'), ('art_ph', '사진'), ('art_pd', '영상 제작'), ('art_de', '디자인'), ('art_ar', '미술'), ('bus_ft', '재테크'), ('bus_fin', '파이낸스'), ('bus_ma', '마케팅'), ('bus_hr', 'HR'), ('bus_sa', '영업')], max_length=186, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='jobs',
            field=multiselectfield.db.fields.MultiSelectField(blank=True, choices=[('대학생', '대학생'), ('취준생', '취준생'), ('주니어 직장인', '주니어 직장인'), ('시니어 직장인', '시니어 직장인')], max_length=23, null=True),
        ),
    ]
