# Generated by Django 3.1.14 on 2022-01-17 02:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20220117_0035'),
        ('accounts', '0002_auto_20220117_0125'),
    ]

    operations = [
    ]
