# Generated by Django 3.1.14 on 2022-05-30 13:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', 'user_plan_update'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='proposal',
            name='user',
        ),
        migrations.AlterField(
            model_name='user_plan',
            name='finish_date',
            field=models.DateField(default=datetime.date(2022, 5, 30)),
        ),
        migrations.AlterField(
            model_name='user_plan',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 5, 30)),
        ),
    ]
