# Generated by Django 3.1.14 on 2022-01-11 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_plan',
            name='rate',
            field=models.IntegerField(default=0),
        ),
    ]
