# Generated by Django 3.1.14 on 2022-01-07 07:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='plan',
            name='writer_img',
            field=models.URLField(blank=True, null=True),
        ),
    ]
