# Generated by Django 3.1.14 on 2022-01-09 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_phone_num'),
        ('plan', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_plan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
        ),
        migrations.AlterField(
            model_name='user_plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.user'),
        ),
    ]
