# Generated by Django 3.1.14 on 2022-01-16 19:46

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_user_plan_rate'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_plan',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_plan',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
