# Generated by Django 3.1.14 on 2022-01-10 07:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20220110_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_plan_todo',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
            preserve_default=False,
        ),
    ]
