# Generated by Django 3.1.14 on 2022-01-07 09:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_auto_20220107_1612'),
    ]

    operations = [
        migrations.RenameField(
            model_name='plan',
            old_name='name1',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='plan',
            name='name2',
        ),
    ]
