# Generated by Django 3.1.14 on 2022-01-07 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_remove_user_phone_num'),
        ('plan', '0003_auto_20220107_1833'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_plan',
            name='plan',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='plans', to='plan.plan'),
        ),
        migrations.AlterField(
            model_name='user_plan',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='users', to='accounts.user'),
        ),
    ]
