# Generated by Django 3.1.14 on 2022-01-10 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0003_user_plan_todo_plan'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_plan_todo',
            name='plan',
        ),
    ]
