# Generated by Django 3.1.14 on 2022-01-07 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_auto_20220107_2323'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_plan',
            name='own_flag',
            field=models.BooleanField(default=False),
        ),
    ]
