# Generated by Django 3.1.14 on 2022-01-10 08:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0004_remove_user_plan_todo_plan'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_todo_video',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user_plan_todo',
            name='plan',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='plan.plan'),
            preserve_default=False,
        ),
    ]
