# Generated by Django 3.1.14 on 2022-01-10 14:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0005_auto_20220110_1714'),
    ]

    operations = [
        migrations.AddField(
            model_name='plan_todo',
            name='media_flag',
            field=models.BooleanField(default=0),
        ),
    ]
