# Generated by Django 3.1.14 on 2022-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', 'plan_migration'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_plan_todo',
            name='day',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
