# Generated by Django 3.1.14 on 2022-04-15 08:45

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('plan', '0002_user_plan_todo_day'),
    ]

    operations = [
        migrations.AddField(
            model_name='user_plan',
            name='finish_date',
            field=models.DateField(default=datetime.date(2022, 4, 15)),
        ),
        migrations.AddField(
            model_name='user_plan',
            name='start_date',
            field=models.DateField(default=datetime.date(2022, 4, 15)),
        ),
    ]
